name: Build STM32F446 FreeRTOS Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install ARM Toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi make

    - name: Build Firmware
      run: |
        make
