name: Build STM32F446 FreeRTOS

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install ARM Toolchain
      run: |
        sudo apt update
        sudo apt install gcc-arm-none-eabi make

    - name: Build with Makefile
      run: make
